from distutils.core import setup

setup(
    name='GenericFlaskApp',
    version='',
    packages=['venv.Lib.distutils', 'venv.Lib.encodings', 'venv.Lib.site-packages.pip',
              'venv.Lib.site-packages.pip.vcs', 'venv.Lib.site-packages.pip._vendor',
              'venv.Lib.site-packages.pip._vendor.distlib', 'venv.Lib.site-packages.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip._vendor.colorama', 'venv.Lib.site-packages.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip._vendor.html5lib.trie', 'venv.Lib.site-packages.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip._vendor.html5lib.serializer',
              'venv.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'venv.Lib.site-packages.pip._vendor.requests',
              'venv.Lib.site-packages.pip._vendor.requests.packages',
              'venv.Lib.site-packages.pip._vendor.requests.packages.chardet',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip._vendor._markerlib', 'venv.Lib.site-packages.pip.commands',
              'venv.Lib.site-packages.pip.backwardcompat', 'venv.Lib.site-packages.flask',
              'venv.Lib.site-packages.flask.ext', 'venv.Lib.site-packages.flask.testsuite',
              'venv.Lib.site-packages.flask.testsuite.test_apps.lib.python2.5.site-packages.site_package',
              'venv.Lib.site-packages.flask.testsuite.test_apps.path.installed_package',
              'venv.Lib.site-packages.flask.testsuite.test_apps.flaskext',
              'venv.Lib.site-packages.flask.testsuite.test_apps.flaskext.oldext_package',
              'venv.Lib.site-packages.flask.testsuite.test_apps.moduleapp',
              'venv.Lib.site-packages.flask.testsuite.test_apps.moduleapp.apps',
              'venv.Lib.site-packages.flask.testsuite.test_apps.moduleapp.apps.admin',
              'venv.Lib.site-packages.flask.testsuite.test_apps.moduleapp.apps.frontend',
              'venv.Lib.site-packages.flask.testsuite.test_apps.blueprintapp',
              'venv.Lib.site-packages.flask.testsuite.test_apps.blueprintapp.apps',
              'venv.Lib.site-packages.flask.testsuite.test_apps.blueprintapp.apps.admin',
              'venv.Lib.site-packages.flask.testsuite.test_apps.blueprintapp.apps.frontend',
              'venv.Lib.site-packages.flask.testsuite.test_apps.flask_broken',
              'venv.Lib.site-packages.flask.testsuite.test_apps.config_package_app',
              'venv.Lib.site-packages.flask.testsuite.test_apps.subdomaintestmodule',
              'venv.Lib.site-packages.flask.testsuite.test_apps.flask_newext_package', 'venv.Lib.site-packages.jinja2',
              'venv.Lib.site-packages.jinja2.testsuite', 'venv.Lib.site-packages.jinja2.testsuite.res',
              'venv.Lib.site-packages.werkzeug', 'venv.Lib.site-packages.werkzeug.debug',
              'venv.Lib.site-packages.werkzeug.contrib', 'venv.Lib.site-packages.werkzeug.testsuite',
              'venv.Lib.site-packages.werkzeug.testsuite.contrib', 'venv.Lib.site-packages._markerlib',
              'venv.Lib.site-packages.markupsafe', 'venv.Lib.site-packages.setuptools',
              'venv.Lib.site-packages.setuptools.tests', 'venv.Lib.site-packages.setuptools.command',
              'venv.Lib.site-packages.sqlalchemy', 'venv.Lib.site-packages.sqlalchemy.ext',
              'venv.Lib.site-packages.sqlalchemy.ext.declarative', 'venv.Lib.site-packages.sqlalchemy.orm',
              'venv.Lib.site-packages.sqlalchemy.sql', 'venv.Lib.site-packages.sqlalchemy.util',
              'venv.Lib.site-packages.sqlalchemy.event', 'venv.Lib.site-packages.sqlalchemy.engine',
              'venv.Lib.site-packages.sqlalchemy.testing', 'venv.Lib.site-packages.sqlalchemy.testing.suite',
              'venv.Lib.site-packages.sqlalchemy.testing.plugin', 'venv.Lib.site-packages.sqlalchemy.dialects',
              'venv.Lib.site-packages.sqlalchemy.dialects.mssql', 'venv.Lib.site-packages.sqlalchemy.dialects.mysql',
              'venv.Lib.site-packages.sqlalchemy.dialects.oracle', 'venv.Lib.site-packages.sqlalchemy.dialects.sqlite',
              'venv.Lib.site-packages.sqlalchemy.dialects.sybase', 'venv.Lib.site-packages.sqlalchemy.dialects.drizzle',
              'venv.Lib.site-packages.sqlalchemy.dialects.firebird',
              'venv.Lib.site-packages.sqlalchemy.dialects.postgresql', 'venv.Lib.site-packages.sqlalchemy.databases',
              'venv.Lib.site-packages.sqlalchemy.connectors', 'venv.Lib.site-packages.flask_restless',
              'venv.Lib.site-packages.flask_sqlalchemy'],
    url='',
    license='',
    author='Valy',
    author_email='',
    description=''
)
